### ISSUE TITLE
[Feature Req.] Support for higher resolutions

### ISSUE THREAD

**Issue by Rajssss** [STMicroelectronics/stm32-ov5640#1]
**Describe the set-up**

 * The board (either ST RPN reference or your custom board) : STM32F746G-DISC
 * IDE or at least the compiler and its version: CUBE IDE 1.7.0

**Describe the bug (skip if none)**

I found that this component doesn't support resolutions higher than 800x480, using a sensor like ov5640 with such capped resolution doesn't makes sense. Is there any plans for adding support for HD (720/1080) resolutions?
I am working on a project which requires this.

**Comment by RKOUSTM** [comment]
Hi @Rajssss,

Thank you for your report. The reported point will be forwarded to our development teams. I will get to you as soon as they provide their feedback.

Thank you again for your report and for your patience.

With regards,

**Comment by RKOUSTM** [comment]
Hi @Rajssss,

Thank you for your report. Unfortunately, there is no plan for our technical team to support higher resolutions on the OV5640 BSP CAMERA component driver as the maximum LCD resolution on our boards is 800x480 and the OmniVision camera is out of the scope of STMicroelectronics. However, according to our development team, the user can create his extension driver where he can add the resolution he needs. 

Please allow me to close this issue now. Thank you again for your report and for your comprehension. I will keep you informed shall there be anything new.  We are looking forward to reading from you again.

With regards,
