### ISSUE TITLE
function name and its comment do not match

### ISSUE THREAD

**Issue by hxhou0207** [STMicroelectronics/stm32-ov5640#2]
ov5640.c line 680 and line 694 function name and its comment do not match

![image](https://github.com/STMicroelectronics/stm32-ov5640/assets/130623428/e40894af-b4d4-4625-ae3a-043d4eefbf4a)

**Comment by ALABSTM** [comment]
Hi @hhx0207,

Any details please about why this issue has been marked as solved?

Thanks,
